export * from "./Dashboard";
export * from "./SignUp";
export * from "./SignIn";
export * from "./Home";
export * from "./CreatePost";
export * from "./UpdatePost";
export * from "./AllPosts";
export * from "./PostPage";
export * from "./Search";